[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = [
  "cd backend && python -m pip install --upgrade pip",
  "cd backend && python -m pip install -r requirements.txt"
]

[start]
cmd = "cd backend && gunicorn api.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120"
