services:
  # Backend API Service
  - type: web
    name: resumeforge-api
    runtime: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt --no-cache-dir
    startCommand: gunicorn backend.api.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: OPENAI_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: WEB_CONCURRENCY
        value: 1
    healthCheckPath: /api/health

  # Frontend Service
  - type: web
    name: resumeforge-frontend
    runtime: node
    region: oregon
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: npm ci --production=false && npm run build
    startCommand: npx serve -s dist -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_API_URL
        value: https://resumeforge-api.onrender.com